### ISSUE TITLE
BUILD_BRANCH just "HEAD" instead of the branch name if checked out by tag

### ISSUE THREAD

**Issue by cookiEoverdose** [SLUB-digitalpreservation/checkit_tiff#8]
checkit_tiff/src/CMakeLists.txt:31

Maybe include tag name (if set)?

**Comment by ghost** [comment]
Fixed in https://github.com/SLUB-digitalpreservation/checkit_tiff/commit/c3cc4125c9d392c0f97f1e283950d55977623b1f
